# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      prefix-security: "fix"
      include: "scope"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    versioning-strategy: increase-if-necessary

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
