from koda.providers.registry import ModelCapabilities, ModelDefinition, ThinkingLevel

MODELS: list[ModelDefinition] = [
    ModelDefinition(
        id="gpt-5.3-codex",
        name="gpt-5.3-codex",
        provider="openai",
        thinking={
            ThinkingLevel.LOW,
            ThinkingLevel.MEDIUM,
            ThinkingLevel.HIGH,
            ThinkingLevel.EXTRA_HIGH,
        },
        capabilities={ModelCapabilities.WEB_SEARCH},
    ),
    ModelDefinition(
        id="gpt-5.2-codex",
        name="gpt-5.2-codex",
        provider="openai",
        thinking={
            ThinkingLevel.LOW,
            ThinkingLevel.MEDIUM,
            ThinkingLevel.HIGH,
            ThinkingLevel.EXTRA_HIGH,
        },
        capabilities={
            ModelCapabilities.WEB_SEARCH,
            ModelCapabilities.EXTENDED_PROMPT_RETENTION,
        },
    ),
    ModelDefinition(
        id="gpt-5.2",
        name="gpt-5.2",
        provider="openai",
        thinking={
            ThinkingLevel.LOW,
            ThinkingLevel.MEDIUM,
            ThinkingLevel.HIGH,
            ThinkingLevel.EXTRA_HIGH,
        },
        capabilities={
            ModelCapabilities.WEB_SEARCH,
            ModelCapabilities.EXTENDED_PROMPT_RETENTION,
        },
    ),
    ModelDefinition(
        id="gpt-5.1-codex",
        name="gpt-5.1-codex",
        provider="openai",
        thinking={
            ThinkingLevel.LOW,
            ThinkingLevel.MEDIUM,
            ThinkingLevel.HIGH,
        },
        capabilities={
            ModelCapabilities.WEB_SEARCH,
            ModelCapabilities.EXTENDED_PROMPT_RETENTION,
        },
    ),
    ModelDefinition(
        id="gpt-5.1",
        name="gpt-5.1",
        provider="openai",
        thinking={
            ThinkingLevel.LOW,
            ThinkingLevel.MEDIUM,
            ThinkingLevel.HIGH,
        },
        capabilities={
            ModelCapabilities.WEB_SEARCH,
            ModelCapabilities.EXTENDED_PROMPT_RETENTION,
        },
    ),
    ModelDefinition(
        id="gpt-5-mini",
        name="gpt-5-mini",
        provider="openai",
        thinking={
            ThinkingLevel.LOW,
            ThinkingLevel.MEDIUM,
            ThinkingLevel.HIGH,
        },
        capabilities={ModelCapabilities.WEB_SEARCH},
    ),
    ModelDefinition(
        id="gpt-5-nano",
        name="gpt-5-nano",
        provider="openai",
        thinking={
            ThinkingLevel.LOW,
            ThinkingLevel.MEDIUM,
            ThinkingLevel.HIGH,
        },
        capabilities={ModelCapabilities.WEB_SEARCH},
    ),
]
